# Llibreries

In [151]:
import pandas as pd
import numpy as np
import os
import json
import sys


# Visualització
import matplotlib.pyplot as plt
import seaborn as sns

# Config vis
sns.set_theme()

## Dimensions
Carrega del dataset que conté totes les dimensions de les dades

In [152]:
dimensions = pd.read_csv("../data/dimensions/pad_dimensions.csv")
dim_barris = pd.read_csv("../data/dimensions/BarcelonaCiutat_Barris.csv")

In [153]:
dim_barris.head()

,codi_districte,nom_districte,codi_barri,nom_barri,geometria_etrs89,geometria_wgs84
0,1,Ciutat Vella,1,el Raval,"POLYGON ((430162.1875 4581936.9845, 430102.838...","POLYGON ((2.16471378585589 41.3859301967194, 2..."
1,1,Ciutat Vella,2,el Barri Gòtic,"POLYGON ((431189.9075 4581851.4475, 431025.789...","POLYGON ((2.1770141884741 41.385248355328, 2.1..."
2,1,Ciutat Vella,3,la Barceloneta,"POLYGON ((432798.7341255 4582081.2599495, 4327...","POLYGON ((2.19622882469513 41.387454220446, 2...."
3,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera","POLYGON ((431733.736 4582441.816, 431557.5115 ...","POLYGON ((2.18345134701381 41.3906119681235, 2..."
4,2,Eixample,5,el Fort Pienc,"POLYGON ((431741.8152 4582625.6491, 432012.183...","POLYGON ((2.18352725722411 41.3922683849226, 2..."

In [154]:
dimensions.head()

,Codi_Dimensio,Desc_Dimensio,Codi_Valor,Desc_Valor_CA,Desc_Valor_ES,Desc_Valor_EN
0,1,SEXE,1,Dona,Mujer,Female
1,1,SEXE,2,Home,Hombre,Male
2,2,EDAT_1,0,0 anys,0 años,0 years
3,2,EDAT_1,1,1 anys,1 años,1 years
4,2,EDAT_1,2,2 anys,2 años,2 years

In [155]:
def neteja_noms_columnes(df):
    """
    Funció per netejar els noms de les columnes d'un DataFrame.
    Elimina espais, converteix a minúscules i reemplaça caràcters especials.
    
    Args:
        df (pd.DataFrame): DataFrame al qual se li vol netejar els noms de les columnes.
    
    Returns:
        pd.DataFrame: DataFrame amb els noms de les columnes netejats.
    """
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('[^a-zA-Z0-9_]', '', regex=True)
    return df

## Dades demogràfiques
Aquests datasets seran utilitzats per extreure atributs demogràfic per al conjunt agregat final.
- Població per barri (Recompte)
- Població per continent de nacionalitat (Recompte)
- Estudis Poblacionals per edat i lloc de naixement

#### Població Total per Barri
Amb aquests arxius obtindrem la població total per barri.

In [156]:
# Import dades
df_poblacio_total_25_raw = pd.read_csv("../data/raw/2025_pad_mdbas.csv")
df_poblacio_total_25_raw.head()

,Data_Referencia,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,AEB,Seccio_Censal,Valor
0,2025-01-01,1,Ciutat Vella,1,el Raval,1,1001,1419
1,2025-01-01,1,Ciutat Vella,1,el Raval,1,1002,1345
2,2025-01-01,1,Ciutat Vella,1,el Raval,2,1003,3710
3,2025-01-01,1,Ciutat Vella,1,el Raval,2,1004,3092
4,2025-01-01,1,Ciutat Vella,1,el Raval,3,1005,2443

In [157]:
df_poblacio_total_15_raw = pd.read_csv("../data/raw/2015_pad_mdbas.csv")
df_poblacio_total_15_raw.head()

,Data_Referencia,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,AEB,Seccio_Censal,Valor
0,2015-01-01,1,Ciutat Vella,1,el Raval,1,1001,1321
1,2015-01-01,1,Ciutat Vella,1,el Raval,1,1002,1528
2,2015-01-01,1,Ciutat Vella,1,el Raval,2,1003,3340
3,2015-01-01,1,Ciutat Vella,1,el Raval,2,1004,2785
4,2015-01-01,1,Ciutat Vella,1,el Raval,3,1005,2460

In [158]:
df_poblacio_total_25_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1068 entries, 0 to 1067
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data_Referencia  1068 non-null   object
 1   Codi_Districte   1068 non-null   int64
 2   Nom_Districte    1068 non-null   object
 3   Codi_Barri       1068 non-null   int64
 4   Nom_Barri        1068 non-null   object
 5   AEB              1068 non-null   int64
 6   Seccio_Censal    1068 non-null   int64
 7   Valor            1068 non-null   int64
dtypes: int64(5), object(3)
memory usage: 66.9+ KB

**Observacions:**
- No hi ha presència de valors nuls
- Atribut valor en format correcte

In [159]:
df_poblacio_total_15_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1068 entries, 0 to 1067
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data_Referencia  1068 non-null   object
 1   Codi_Districte   1068 non-null   int64
 2   Nom_Districte    1068 non-null   object
 3   Codi_Barri       1068 non-null   int64
 4   Nom_Barri        1068 non-null   object
 5   AEB              1068 non-null   int64
 6   Seccio_Censal    1068 non-null   int64
 7   Valor            1068 non-null   int64
dtypes: int64(5), object(3)
memory usage: 66.9+ KB

**Observacions:**
- Igual que amb les dades de 2025

In [160]:
df_poblacio_total_15 = df_poblacio_total_15_raw.groupby("Codi_Barri").agg({"Valor": "sum"}).reset_index()
df_poblacio_total_25 = df_poblacio_total_25_raw.groupby("Codi_Barri").agg({"Valor": "sum"}).reset_index()

In [161]:
df_poblacio_total_25.rename(columns={"Valor": "Poblacio_Total"}, inplace=True)
df_poblacio_total_15.rename(columns={"Valor": "Poblacio_Total"}, inplace=True)

#### Població per barri per Nacionalitat (Esp, resta Unió Europea, resta món)
Per aquest indicador es processaran dos fitxers per als dos anys. En un primer, obtindrem la població espanyola resident als barris. Posteriorment, utilitzarem un segon conjunt de dades amb la població desglosada per continents de nacionalitat. A partir d'aquests dos fitxers podrem extreure indicadors relacionats amb les proporcions de població estrangera en els barris, i inclos segmentar-la per continents.

In [162]:
# Població

df_poblacio_25 = pd.read_csv('../data/raw/2025_pad_mdbas_nacionalitat-g_sexe.csv')
df_poblacio_25.head()

,Data_Referencia,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,AEB,Seccio_Censal,Valor,NACIONALITAT_G,SEXE
0,2025-01-01,1,Ciutat Vella,1,el Raval,1,1001,349,1,1
1,2025-01-01,1,Ciutat Vella,1,el Raval,1,1001,375,1,2
2,2025-01-01,1,Ciutat Vella,1,el Raval,1,1001,69,2,1
3,2025-01-01,1,Ciutat Vella,1,el Raval,1,1001,74,2,2
4,2025-01-01,1,Ciutat Vella,1,el Raval,1,1001,260,3,1

In [163]:
df_poblacio_25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6665 entries, 0 to 6664
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data_Referencia  6665 non-null   object
 1   Codi_Districte   6665 non-null   int64
 2   Nom_Districte    6665 non-null   object
 3   Codi_Barri       6665 non-null   int64
 4   Nom_Barri        6665 non-null   object
 5   AEB              6665 non-null   int64
 6   Seccio_Censal    6665 non-null   int64
 7   Valor            6665 non-null   object
 8   NACIONALITAT_G   6665 non-null   int64
 9   SEXE             6665 non-null   int64
dtypes: int64(6), object(4)
memory usage: 520.8+ KB

**Observacions:**
- No es detecten nuls
- Atribut de valor identificat com a object.

In [164]:
# Població

df_poblacio_15 = pd.read_csv('../data/raw/2015_pad_mdbas_nacionalitat-g_sexe.csv')
df_poblacio_15.head()

,Data_Referencia,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,AEB,Seccio_Censal,Valor,NACIONALITAT_G,SEXE
0,2015-01-01,1,Ciutat Vella,1,el Raval,1,1001,345,1,1
1,2015-01-01,1,Ciutat Vella,1,el Raval,1,1001,397,1,2
2,2015-01-01,1,Ciutat Vella,1,el Raval,1,1001,68,2,1
3,2015-01-01,1,Ciutat Vella,1,el Raval,1,1001,79,2,2
4,2015-01-01,1,Ciutat Vella,1,el Raval,1,1001,160,3,1

In [165]:
df_poblacio_15.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6582 entries, 0 to 6581
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data_Referencia  6582 non-null   object
 1   Codi_Districte   6582 non-null   int64
 2   Nom_Districte    6582 non-null   object
 3   Codi_Barri       6582 non-null   int64
 4   Nom_Barri        6582 non-null   object
 5   AEB              6582 non-null   int64
 6   Seccio_Censal    6582 non-null   int64
 7   Valor            6582 non-null   object
 8   NACIONALITAT_G   6582 non-null   int64
 9   SEXE             6582 non-null   int64
dtypes: int64(6), object(4)
memory usage: 514.3+ KB

**Observacions:**
- Mateixes observacions que al dataset de 2025

In [166]:
df_poblacio_25[df_poblacio_25["Valor"] == ".."]

,Data_Referencia,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,AEB,Seccio_Censal,Valor,NACIONALITAT_G,SEXE
12,2025-01-01,1,Ciutat Vella,1,el Raval,1,1002,..,4,1
19,2025-01-01,1,Ciutat Vella,1,el Raval,2,1003,..,4,2
26,2025-01-01,1,Ciutat Vella,1,el Raval,2,1004,..,4,1
33,2025-01-01,1,Ciutat Vella,1,el Raval,3,1005,..,4,1
40,2025-01-01,1,Ciutat Vella,1,el Raval,3,1006,..,4,1
...,...,...,...,...,...,...,...,...,...,...
6530,2025-01-01,10,Sant Martí,72,Sant Martí de Provençals,229,10121,..,4,2
6552,2025-01-01,10,Sant Martí,73,la Verneda i la Pau,230,10125,..,2,2
6557,2025-01-01,10,Sant Martí,73,la Verneda i la Pau,230,10126,..,2,1
6609,2025-01-01,10,Sant Martí,73,la Verneda i la Pau,231,10134,..,4,1
6634,2025-01-01,10,Sant Martí,73,la Verneda i la Pau,232,10138,..,4,1

**Observacions**
- Segons el portal de dades, els valors marcats com a ".." són menors de 5.
- Per tal de no eliminar del dataset aquests valors, els imputem amb un número dins del rang per tal de mantenir informació sense esbiaixar els resultats.

In [167]:
# Convertim valors ".." a NaN 
df_poblacio_25["Valor"] = df_poblacio_25["Valor"].replace("..", 4)
df_poblacio_15["Valor"] = df_poblacio_15["Valor"].replace("..", 4)

In [168]:
# Convertir la columna "Valor" a int32
df_poblacio_25["Valor"] = df_poblacio_25["Valor"].astype(str).astype("Int32")
df_poblacio_15["Valor"] = df_poblacio_15["Valor"].astype(str).astype("Int32")

In [169]:
# Agregar a població per barri i nacionalitat. Ignorem sexe
df_poblacio_15_agg = df_poblacio_15.groupby(["Codi_Barri", "NACIONALITAT_G"]).agg({"Valor": "sum"}).reset_index()
df_poblacio_25_agg = df_poblacio_25.groupby(["Codi_Barri", "NACIONALITAT_G"]).agg({"Valor": "sum"}).reset_index()

In [170]:
df_poblacio_15_agg.head()

   Codi_Barri  NACIONALITAT_G  Valor
0           1               1  24498
1           1               2   4347
2           1               3  18293
3           1               4     44
4           2               1   9007

In [171]:
df_poblacio_25_agg.head()

   Codi_Barri  NACIONALITAT_G  Valor
0           1               1  23364
1           1               2   5064
2           1               3  21471
3           1               4     60
4           2               1   8903

Creuarem amb la dimensió de nacionalitats i posteriorment pivotarem la columna per obtenir una columna per cada tipus de nacionalitat.

In [172]:
# Definim la dimensió
dim_nacionalitat_g = dimensions[dimensions["Desc_Dimensio"] == "NACIONALITAT_G"]
dim_nacionalitat_g.head()

,Codi_Dimensio,Desc_Dimensio,Codi_Valor,Desc_Valor_CA,Desc_Valor_ES,Desc_Valor_EN
176,7,NACIONALITAT_G,1,Espanya,España,Spain
177,7,NACIONALITAT_G,2,Resta de la Unió Europea,Resto de la Unión Europea,Rest of European Union
178,7,NACIONALITAT_G,3,Resta del món,Resto del mundo,Rest of World
179,7,NACIONALITAT_G,4,No consta,No consta,Not available

In [173]:
df_poblacio_25_merged = df_poblacio_25_agg.merge(dim_nacionalitat_g[["Codi_Valor","Desc_Valor_CA"]], left_on="NACIONALITAT_G", right_on="Codi_Valor", how="left")
df_poblacio_25_merged.head()

   Codi_Barri  NACIONALITAT_G  Valor  Codi_Valor             Desc_Valor_CA
0           1               1  23364           1                   Espanya
1           1               2   5064           2  Resta de la Unió Europea
2           1               3  21471           3             Resta del món
3           1               4     60           4                 No consta
4           2               1   8903           1                   Espanya

In [174]:
df_poblacio_15_merged = df_poblacio_15_agg.merge(dim_nacionalitat_g[["Codi_Valor","Desc_Valor_CA"]], left_on="NACIONALITAT_G", right_on="Codi_Valor", how="left")
df_poblacio_15_merged.head()

   Codi_Barri  NACIONALITAT_G  Valor  Codi_Valor             Desc_Valor_CA
0           1               1  24498           1                   Espanya
1           1               2   4347           2  Resta de la Unió Europea
2           1               3  18293           3             Resta del món
3           1               4     44           4                 No consta
4           2               1   9007           1                   Espanya

In [175]:
# Pivotem
df_pob_25_pivot = df_poblacio_25_merged.pivot_table(index=["Codi_Barri"], columns="Desc_Valor_CA", values=["Valor"], fill_value=0).droplevel(0, axis=1).reset_index()
df_pob_15_pivot = df_poblacio_15_merged.pivot_table(index=["Codi_Barri"], columns="Desc_Valor_CA", values=["Valor"], fill_value=0).droplevel(0, axis=1).reset_index()

In [176]:
# Netejem indexs i columnes
df_pob_25_pivot.columns.name = None
df_pob_25_pivot = df_pob_25_pivot.reset_index(drop=True)

df_pob_15_pivot.columns.name = None
df_pob_15_pivot = df_pob_15_pivot.reset_index(drop=True)

### Població per Regió (Amèrca del Nord, Europa Occidental, etc.)

In [177]:
df_nacionalitats_25 = pd.read_csv("../data/raw/2025_pad_mdb_nacionalitat-regio_sexe.csv")
df_nacionalitats_15 = pd.read_csv("../data/raw/2015_pad_mdb_nacionalitat-regio_sexe.csv")

In [178]:
dim_regions = dimensions[dimensions["Desc_Dimensio"] == "NACIONALITAT_REGIO"]

In [179]:
df_nacionalitats_25.head()

,Data_Referencia,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Valor,NACIONALITAT_REGIO,SEXE
0,2025-01-01,1,Ciutat Vella,1,el Raval,20,1,1
1,2025-01-01,1,Ciutat Vella,1,el Raval,31,1,2
2,2025-01-01,1,Ciutat Vella,1,el Raval,12,2,1
3,2025-01-01,1,Ciutat Vella,1,el Raval,15,2,2
4,2025-01-01,1,Ciutat Vella,1,el Raval,695,3,1

In [180]:
df_nacionalitats_25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2681 entries, 0 to 2680
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Data_Referencia     2681 non-null   object
 1   Codi_Districte      2681 non-null   int64
 2   Nom_Districte       2681 non-null   object
 3   Codi_Barri          2681 non-null   int64
 4   Nom_Barri           2681 non-null   object
 5   Valor               2681 non-null   object
 6   NACIONALITAT_REGIO  2681 non-null   int64
 7   SEXE                2681 non-null   int64
dtypes: int64(4), object(4)
memory usage: 167.7+ KB

**Observacions:**
- No hi ha nuls, però Valor torna a estar com a obj, indicant que hi pot haver valors ".."

In [181]:
df_nacionalitats_15.head()

,Data_Referencia,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Valor,NACIONALITAT_REGIO,SEXE
0,2015-01-01,1,Ciutat Vella,1,el Raval,..,1,1
1,2015-01-01,1,Ciutat Vella,1,el Raval,..,1,2
2,2015-01-01,1,Ciutat Vella,1,el Raval,5,2,1
3,2015-01-01,1,Ciutat Vella,1,el Raval,14,2,2
4,2015-01-01,1,Ciutat Vella,1,el Raval,621,3,1

In [182]:
# Convertim valors ".." a NaN 
df_nacionalitats_15["Valor"] = df_nacionalitats_15["Valor"].replace("..", 4)
df_nacionalitats_25["Valor"] = df_nacionalitats_25["Valor"].replace("..", 4)

In [183]:
# Convertir la columna "Valor" a int32
df_nacionalitats_25["Valor"] = df_nacionalitats_25["Valor"].astype(str).astype("Int32")
df_nacionalitats_15["Valor"] = df_nacionalitats_15["Valor"].astype(str).astype("Int32")

In [184]:
# Agregar a població per barri i nacionalitat. Ignorem sexe
df_nacionalitats_25_agg = df_nacionalitats_25.groupby(["Codi_Barri", "NACIONALITAT_REGIO"]).agg({"Valor": "sum"}).reset_index()
df_nacionalitats_15_agg = df_nacionalitats_15.groupby(["Codi_Barri", "NACIONALITAT_REGIO"]).agg({"Valor": "sum"}).reset_index()

In [185]:
df_nacionalitats_25_merged =df_nacionalitats_25_agg.merge(dim_regions[["Codi_Valor","Desc_Valor_CA"]], left_on="NACIONALITAT_REGIO", right_on="Codi_Valor", how="left")
df_nacionalitats_15_merged =df_nacionalitats_15_agg.merge(dim_regions[["Codi_Valor","Desc_Valor_CA"]], left_on="NACIONALITAT_REGIO", right_on="Codi_Valor", how="left")

In [186]:
df_nacionalitats_25_pivot = df_nacionalitats_25_merged.pivot_table(index=["Codi_Barri"], columns="Desc_Valor_CA", values=["Valor"], fill_value=0).droplevel(0, axis=1).reset_index()
df_nacionalitats_15_pivot = df_nacionalitats_15_merged.pivot_table(index=["Codi_Barri"], columns="Desc_Valor_CA", values=["Valor"], fill_value=0).droplevel(0, axis=1).reset_index()

In [187]:
df_nacionalitats_15_pivot.columns.name = None
df_nacionalitats_15_pivot = df_nacionalitats_15_pivot.reset_index(drop=True)

df_nacionalitats_25_pivot.columns.name = None
df_nacionalitats_25_pivot = df_nacionalitats_25_pivot.reset_index(drop=True)

### Agregacions
En aquest apartat final de les dades demogràfiques, agregarem els conjunts en un sol

In [193]:
# Unifiquem dades de 2025
df_poblacio_agg_25 = df_pob_25_pivot.merge(df_nacionalitats_25_pivot, on="Codi_Barri", how="left")
df_poblacio_agg_25 = df_poblacio_agg_25.merge(df_poblacio_total_25[["Codi_Barri", "Poblacio_Total"]], on="Codi_Barri", how="left")
df_pob_agg_25_clean = neteja_noms_columnes(df_poblacio_agg_25)
df_pob_agg_25_clean.head()

,codi_barri,espanya,no_consta_x,resta_de_la_uni_europea,resta_del_mn,amrica_central,amrica_del_nord,amrica_del_sud,austrlia_i_nova_zelanda,carib,...,frica_meridional,frica_occidental,frica_oriental,frica_septentrional,sia_central,sia_meridional,sia_occidental,sia_oriental,sia_sudoriental,poblacio_total
0,1,23364.0,60.0,5064.0,21471.0,527.0,436.0,3488.0,43.0,323.0,...,15.0,245.0,51.0,2398.0,33.0,7768.0,424.0,474.0,3901.0,49917
1,2,8903.0,20.0,3415.0,15552.0,461.0,396.0,2449.0,63.0,130.0,...,14.0,288.0,23.0,2073.0,25.0,7750.0,299.0,160.0,374.0,27878
2,3,8199.0,16.0,2753.0,3793.0,207.0,162.0,1336.0,30.0,64.0,...,8.0,35.0,9.0,495.0,9.0,557.0,144.0,65.0,42.0,14749
3,4,11667.0,32.0,4565.0,6526.0,309.0,513.0,1751.0,69.0,176.0,...,17.0,106.0,11.0,718.0,19.0,657.0,296.0,301.0,308.0,22767
4,5,23397.0,24.0,4039.0,9175.0,608.0,218.0,3533.0,27.0,114.0,...,20.0,112.0,17.0,884.0,16.0,1096.0,234.0,1292.0,117.0,36621

In [192]:
# Unifiquem dades de 2015
df_poblacio_agg_15 = df_pob_15_pivot.merge(df_nacionalitats_15_pivot, on="Codi_Barri", how="left")
df_poblacio_agg_15 = df_poblacio_agg_15.merge(df_poblacio_total_15[["Codi_Barri", "Poblacio_Total"]], on="Codi_Barri", how="left")
df_pob_agg_15_clean = neteja_noms_columnes(df_poblacio_agg_15)
df_pob_agg_15_clean.head()

,codi_barri,espanya,no_consta_x,resta_de_la_uni_europea,resta_del_mn,amrica_central,amrica_del_nord,amrica_del_sud,austrlia_i_nova_zelanda,carib,...,frica_meridional,frica_occidental,frica_oriental,frica_septentrional,sia_central,sia_meridional,sia_occidental,sia_oriental,sia_sudoriental,poblacio_total
0,1,24498.0,44.0,4347.0,18293.0,292.0,177.0,1862.0,12.0,305.0,...,8.0,173.0,8.0,1532.0,8.0,8742.0,321.0,346.0,4077.0,47150
1,2,9007.0,20.0,3079.0,3422.0,182.0,164.0,772.0,24.0,76.0,...,8.0,105.0,8.0,364.0,17.0,874.0,117.0,220.0,220.0,15514
2,3,10331.0,4.0,2178.0,2527.0,87.0,95.0,734.0,17.0,71.0,...,8.0,39.0,8.0,450.0,9.0,564.0,71.0,87.0,21.0,15037
3,4,13644.0,44.0,4146.0,4666.0,221.0,227.0,1121.0,41.0,213.0,...,5.0,158.0,4.0,815.0,8.0,655.0,130.0,449.0,299.0,22468
4,5,25417.0,36.0,2340.0,3778.0,261.0,72.0,1247.0,8.0,136.0,...,4.0,81.0,8.0,190.0,12.0,265.0,85.0,1119.0,38.0,31548

### Feature Engineering i neteja final
En aquest apartat enriquirem els datasets amb algunes variables porcentuals que ens ajudaran a modelar segons el nostre objectiu.
- Població Total
- % població estrangera
- % població espanyola
- % estragners_occidentals (Amèrica del Nord i Europa) - Article Lopez Gay o Cocola Gant?

Finalment, eliminarem les columnes innecessaries i exportarem fitxer per a cada any net.

In [191]:
dim_regions["Desc_Valor_CA"].unique()

array(['Àfrica oriental', 'Àfrica central', 'Àfrica septentrional',
       'Àfrica meridional', 'Àfrica occidental', 'Carib',
       'Amèrica central', 'Amèrica del sud', 'Amèrica del nord',
       'Àsia central', 'Àsia oriental', 'Àsia meridional',
       'Àsia sud-oriental', 'Àsia occidental', 'Europa oriental',
       'Europa septentrional', 'Europa meridional', 'Europa occidental',
       'Austràlia i Nova Zelanda', 'Melanèsia', 'Micronèsia', 'Polinèsia',
       'No consta'], dtype=object)

En el càlcul de població estrangera occidental considerarem només les regions d' Amèrica del nord i Europa. Per tant, els valors per al càlcul són:
- Amèrica del nord ()
- Resta de la Unió Europea (Població per barri per nacionalitat)

Aquest indicador ens permetrà estudiar com atribut individual la immigració de països amb major poder adquisitiu.

In [194]:
# Calcul de percentatges
df_pob_25_final = df_pob_agg_25_clean.copy()
df_pob_25_final["pct_pob_estrangera"] = 1 -(df_pob_25_final["espanya"] / df_pob_25_final["poblacio_total"])
df_pob_25_final["pct_pob_estrangera_occidental"] = (df_pob_25_final["resta_de_la_uni_europea"] + df_pob_25_final["amrica_del_nord"]) / df_pob_25_final["poblacio_total"]
df_pob_25_final["pct_pob_espanyola"] = df_pob_25_final["espanya"] / df_pob_25_final["poblacio_total"]

In [196]:
df_pob_25_final = df_pob_25_final[["codi_barri", "poblacio_total", "pct_pob_estrangera", "pct_pob_estrangera_occidental", "pct_pob_espanyola"]]
df_pob_25_final.head()

,codi_barri,poblacio_total,pct_pob_estrangera,pct_pob_estrangera_occidental,pct_pob_espanyola
0,1,49917,0.531943,0.110183,0.468057
1,2,27878,0.680644,0.136703,0.319356
2,3,14749,0.444098,0.197641,0.555902
3,4,22767,0.487548,0.223042,0.512452
4,5,36621,0.361104,0.116245,0.638896

In [197]:
# Calcul de percentatges
df_pob_15_final = df_pob_agg_15_clean.copy()
df_pob_15_final["pct_pob_estrangera"] = 1 -(df_pob_15_final["espanya"] / df_pob_15_final["poblacio_total"])
df_pob_15_final["pct_pob_estrangera_occidental"] = (df_pob_15_final["resta_de_la_uni_europea"] + df_pob_15_final["amrica_del_nord"]) / df_pob_15_final["poblacio_total"]
df_pob_15_final["pct_pob_espanyola"] = df_pob_15_final["espanya"] / df_pob_15_final["poblacio_total"]

In [198]:
df_pob_15_final = df_pob_15_final[["codi_barri", "poblacio_total", "pct_pob_estrangera", "pct_pob_estrangera_occidental", "pct_pob_espanyola"]]
df_pob_15_final.head()

,codi_barri,poblacio_total,pct_pob_estrangera,pct_pob_estrangera_occidental,pct_pob_espanyola
0,1,47150,0.480424,0.095949,0.519576
1,2,15514,0.419428,0.209037,0.580572
2,3,15037,0.312961,0.15116,0.687039
3,4,22468,0.392736,0.194632,0.607264
4,5,31548,0.194339,0.076455,0.805661

In [199]:
dimensions[dimensions["Desc_Dimensio"] == "LLOC_NAIX"]["Desc_Valor_CA"].unique()

array(['Barcelona ciutat', 'Resta de Catalunya', 'Resta d’Espanya',
       'Resta de la Unió Europea', 'Resta del món', 'No consta'],
      dtype=object)

## Dades econòmiques

## Dades Urbanes